//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsSupport
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryOrder
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public Nullable<System.DateTime> DateChange { get; set; }
        public int StatusOrderID { get; set; }
        public int EmployeeID { get; set; }
        public int RoomID { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
