//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsSupport
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryKartridj
    {
        public int ID { get; set; }
        public int KartridjID { get; set; }
        public System.DateTime DateChange { get; set; }
        public int StatusID { get; set; }
        public int RoomID { get; set; }
    
        public virtual Kartridjs Kartridjs { get; set; }
    }
}
