//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsSupport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IsSupportContext : DbContext
    {
        public IsSupportContext()
            : base("name=IsSupportContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Computers> Computers { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Equipments> Equipments { get; set; }
        public virtual DbSet<HistoryKartridj> HistoryKartridj { get; set; }
        public virtual DbSet<HistoryOrder> HistoryOrder { get; set; }
        public virtual DbSet<Kartridjs> Kartridjs { get; set; }
        public virtual DbSet<Keyboards> Keyboards { get; set; }
        public virtual DbSet<Monitors> Monitors { get; set; }
        public virtual DbSet<Mouse> Mouse { get; set; }
        public virtual DbSet<MultimediaSystems> MultimediaSystems { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OS> OS { get; set; }
        public virtual DbSet<Printers> Printers { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<StatusKartridj> StatusKartridj { get; set; }
        public virtual DbSet<StatusOrders> StatusOrders { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeComponent> TypeComponent { get; set; }
        public virtual DbSet<TypesEquipment> TypesEquipment { get; set; }
        public virtual DbSet<StatusDevice> StatusDevice { get; set; }
        public virtual DbSet<SystemUnits> SystemUnits { get; set; }
        public virtual DbSet<Components> Components { get; set; }
        public virtual DbSet<SystemUnitComponents> SystemUnitComponents { get; set; }
    }
}
