//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsSupport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kartridjs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kartridjs()
        {
            this.HistoryKartridj = new HashSet<HistoryKartridj>();
        }

        public int ID { get; set; }
        public string Title { get; set; }
        public string NumberOfKartridj { get; set; }
        public int PrinterID { get; set; }
        public int RoomID { get; set; }
        public Nullable<System.DateTime> DatePay { get; set; }
        public string Image { get; set; }
        public int StatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryKartridj> HistoryKartridj { get; set; }
        public virtual Printers Printers { get; set; }
        public virtual Rooms Rooms { get; set; }
        public virtual StatusKartridj StatusKartridj { get; set; }
    }
}
