//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsSupport
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUnitComponents
    {
        public int ID { get; set; }
        public int SystemUnitID { get; set; }
        public int ComponentID { get; set; }
        public int Count { get; set; }
    
        public virtual Components Components { get; set; }
        public virtual SystemUnits SystemUnits { get; set; }
    }
}
